### ISSUE TITLE
+[editor]: Support jar in preview

### ISSUE THREAD

**Issue by KingNucifera** [AdamRaichu/vscode-zip-viewer#97] opened 2024-02-12 06:38 UTC
Please add support for `.jar` files to the editor preview.

*Generated by `adamraichu.zip-viewer`*

**Comment by KavyanshKhaitan2** [comment] 2024-06-09 04:19
Should be as simple as the `.zip` preview, since in reality, `.jar` files are just glorified `.zip` files.

**Comment by AdamRaichu** [comment] 2024-08-10 14:05
Sorry for such a late response, and for the negative response, but...

Duplicate of #46.

> Sorry, but I don't plan to support previewing zip files inside of zip files. Instead, use the [selective extraction](https://github.com/AdamRaichu/vscode-zip-viewer#selective-extraction) feature to extract the zip you want to preview, then open it normally.

**Closed by AdamRaichu** 2024-08-10 14:05 UTC
